### ISSUE TITLE
Map View Bugs

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-android#1]
1. Does not display icons when zoomed out too far.
2. Only loads a small number of Hurricane Ian cases.
3. Circle icons are cut off at the edges of tiles, it appears. See screenshots.

![Image](https://user-images.githubusercontent.com/4184619/219464731-459c804a-cfc0-47d0-b6a7-24d3bcff3efb.jpg)

![Image](https://user-images.githubusercontent.com/4184619/219465118-673ce605-9e8a-4405-827a-70a8dd95decb.jpg)

![Image](https://user-images.githubusercontent.com/4184619/219465315-6a8b13b9-b2cb-4f93-8513-2402a1183267.jpg)

**Comment by hueachilles** [comment]
These are fixed with build 21

**Comment by hueachilles** [comment]
Commit 04b5a265b73265cce39f12157a6726d50211617f (and prior)
