### ISSUE TITLE
Keep Photos I've added

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-android#10]
1. Add new photos to a case.
2. Sync.
3. Re-open the case. Bug: The photos are gone. They should be available.

![Image](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/4184619/8a54a3c5-f1e5-465b-af23-5fdfc41a35aa)

**Comment by hueachilles** [comment]
Something seems off. The screenshot shows you're not connected to the internet. I was just unable to reproduce but I'm thinking it may have something to do with an expired token. If you logged in does the photo show up?

**Comment by arroyoDev** [comment]
did more testing and I could not get this to break (including doing the steps above.
