### ISSUE TITLE
Request Case UI

### ISSUE THREAD

**Issue by hueachilles** [CrisisCleanup/crisiscleanup-android#11]
From Gina

I'm assuming the sentences are examples they could type in the 'Reasons Requested' field. If so, maybe label them as such and move them by the field.

**Comment by hueachilles** [comment]
I've moved the text around and updated the text styling to be consistent with the rest of the app. The example reasons were moved to be just above the reasons input. Here's how it looks now.

![Screenshot_20230607_075519](https://github.com/CrisisCleanup/crisiscleanup-android/assets/7587194/59c5393c-6799-4929-83c6-73923040c0c5)

**Comment by hueachilles** [comment]
I just noticed the trailing "}" in each example reason. I'll remove it.

**Comment by arroyoDev** [comment]
Changes look good.
