### ISSUE TITLE
Location workflow must match web

### ISSUE THREAD

**Issue by hueachilles** [CrisisCleanup/crisiscleanup-android#16]
- Hide address search bar similarly
- Toggle address fields similarly. This behavior is not completely tied to "Address Problems"
- Render static address similarly

**Comment by hueachilles** [comment]
There will be one deviation from the web. Web presents options when searching the Street address field. I'm omitting that from mobile because options are annoying when you just want to type and the screen keyboard is what you're using.
The location/address search bar still present options.

**Comment by arroyoDev** [comment]
Addresses seam to be handled well.  not sure what the other items mean on this.   Looks good to me.
