### ISSUE TITLE
Testing Mode Intro Pop UP.

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-android#24]
On first load up. we need a big 'acknowledgment screen' that says the following:   

Testing Mode
1.  Thank you for helping us test. Please click the yellow "?" button to report problems.
2.  This is all test data. Adding, editing, or removing data will not mess anything up.
3.  DO NOT use this app for a live incident. All changes are erased every night.

**Comment by hueachilles** [comment]
I'm assuming this can wait until the feedback endpoint is ready?
