### ISSUE TITLE
Bugs Muck Bug:  Reported from Aaron

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-android#31]
- [ ] Bug: in Airplane mode, create new case with muckout, debris, and tree work. Claim debris. Go back to the map and click on the case so edit. Claim muck out. Change status of muckout  BUG: can't do it. Only debris will update.

**Comment by hueachilles** [comment]
v0.1.18

**Comment by arroyoDev** [comment]
Looks like it works.
