### ISSUE TITLE
Bug:  street map does not show detailed local streets.

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-android#33]
- [ ] Bug: The street map is not detailed when zoomed in completely. Local streets missing. 
reported by Aaron.

**Comment by hueachilles** [comment]
v0.1.18

**Comment by arroyoDev** [comment]
android maps still very vague.  no detailed streets.

**Comment by arroyoDev** [comment]
Looks like this has. been resolved with detail steet level maps now.  Well done.
