### ISSUE TITLE
Bug:  Share is not working

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-android#34]
- [ ] Be able to share via text message
- [ ] Be able to share via email.

I validated user testing... neither sent anything to me via text or email.   

**Additional Information:**
- Environment:
- Version:
- Ticket Submitted From: **file:///android_res/raw/user_feedback_form.html?accountCcid=14579**
- Zendesk Username: **JAY HAMON**
- Crisis Cleanup Username: **Jay Hamon**
- Organization: **Montgomery Alabama Stake, The Church of Jesus Christ of Latter-day Saints**
- Email: **silookde@gmail.com**
- Phone: **1 (470) 868-5050**
- CC Age: **3 years ago**

**Pictures:**

**Comments:**
```
  **Comment JAY HAMON:**

Testing new App.  Was not able to send text or email when I tried to share.  It appeared to send but nothing was received

---

**Comment Ross Arroyo:**

https://crisiscleanup.org/incident/278/work
```

**Comment by hueachilles** [comment]
Sharing won't send messages of any kind on staging environment
