### ISSUE TITLE
Responsive issue on share

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-android#55]
Reporting responsive issue on the share page.  

- [ ] make page responsive and text to fit

![Image](https://github.com/CrisisCleanup/crisiscleanup-android/assets/699333/9a2d1f86-a856-4858-90db-02b7e78e4fdd)

**Comment by hueachilles** [comment]
@arroyoDev 
Does this belong in web project?

**Comment by arroyoDev** [comment]
@hueachilles you are super correct.  Android version of share looking good.
