### ISSUE TITLE
Do not put a dark semi-transparent covering over the top of the screen

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-android#6]
See CrisisCleanup/crisiscleanup-4-web#1 on image. The top of the screen is covered by a dark overlay. I kinda don't like it, and it seems like something is wrong or incongruent. Just let the top of the page remain the same (i.e. white).

![Image](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/4184619/0a2883ed-b461-428f-a5c1-0e4761c5c0c7)

**Comment by hueachilles** [comment]
I'll change it to the same shade of color as the bottom navigation bar (dark grey). If this doesn't work we can discuss it during design standup.

![dark-system-bar](https://github.com/CrisisCleanup/crisiscleanup-android/assets/7587194/bb6792c3-4b9c-4bae-88f0-5c90b22f9734)

**Comment by arroyoDev** [comment]
Looks good now.   I think this is fine.
